[workspace]

members = [ "address", "merkle", "mulmsgsig",  "rangeproof", "readerwriter", "starsig", "transaction", "transactionapi","utxo-in-memory", "zkvm", "chain-oracle"]
exclude = ["elgamalsign"]

