[package]
name = "starsig"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A pure-Rust implementation of Schnorr signatures using Ristretto"
repository.workspace = true
readme = "README.md"
categories = ["cryptography"]
keywords = ["cryptography", "crypto", "signatures", "schnorr", "batch"]
publish = false

# documentation = "https://docs.rs/"
# license, repository, authors inherited from [workspace.package]


[dependencies]
thiserror.workspace = true
merlin.workspace = true
rand_core.workspace = true
rand.workspace = true
curve25519-dalek.workspace = true
serde.workspace = true
hex.workspace = true

[features]
default = []
nightly = ["curve25519-dalek/alloc"]
