[package]
name = "address"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A Rust crate for creating, parsing, and validating ZkOS addresses with support for standard and script address types."
repository.workspace = true
readme = "README.md"
categories = ["cryptography", "blockchain", "encoding"]
keywords = ["cryptography", "blockchain", "address", "zkos", "base58", "encoding"]

#documentation = "https://docs.rs/zkos-address"
# license, repository, authors inherited from [workspace.package]


[dependencies]
curve25519-dalek.workspace = true
serde.workspace = true
hex.workspace = true
merlin.workspace = true
sha3.workspace = true
bs58.workspace = true
ripemd.workspace = true
quisquis-rust.workspace = true


[features]
default = []
nightly = ["curve25519-dalek/alloc"]


[dev-dependencies]
criterion = "0.5"
serde_json.workspace = true