[package]
name = "zkvm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Zero-knowledge virtual machine for state transition proofs in ZkOS"
repository.workspace = true
readme = "README.md"

categories = ["cryptography", "blockchain"]
keywords = ["cryptography", "blockchain", "zero-knowledge", "bulletproofs","vm", "smart-contracts"]

publish = false
# documentation = "https://docs.rs/zkvm"
# license, repository, authors inherited from [workspace.package]

[dependencies]
thiserror.workspace = true
byteorder.workspace = true
merlin.workspace = true
rand.workspace = true
subtle.workspace = true
curve25519-dalek.workspace = true
serde.workspace = true
subtle-encoding.workspace = true
hex.workspace = true
bincode.workspace = true


[dependencies.readerwriter]
path = "../readerwriter"
features = ["merlin"]

[dependencies.merkle]
path = "../merkle"

[dependencies.rangeproof]
path = "../rangeproof"

[dependencies.starsig]
path = "../starsig"

[dependencies.mulmsgsig]
path = "../mulmsgsig"

[dependencies.address]
path = "../address"

[dependencies.zkschnorr]
workspace = true

[dependencies.bulletproofs]
workspace = true

[dependencies.quisquis-rust]
workspace = true


[features]
default = []
nightly = ["curve25519-dalek/alloc", "bulletproofs/nightly"]


[dev-dependencies]
criterion = "0.2"
serde_json.workspace = true
