[package]
name = "chain-oracle"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A Rust library for connecting to a Cosmos-based blockchain, retrieving, parsing, and analyzing blocks and transactions—designed for integration with ZkOS and related systems."
repository.workspace = true

readme = "README.md"
keywords = ["cosmos", "blockchain", "oracle", "indexer", "zkvm"]
categories = ["cryptography", "blockchain", "data-structures"]

publish = false
# documentation = "https://docs.rs/nyks-chain-oracle"
# license, repository, authors inherited from [workspace.package]

[lib]
name = "chain_oracle"
path = "src/lib.rs"

[dependencies]
serde.workspace = true  
serde_json.workspace = true
hex.workspace = true
bincode.workspace = true
sha3.workspace = true
sha2.workspace = true

serde_with = { version = "1.4.0", features = ["json"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
base64 = "0.22.0"
stopwatch = "0.0.7"
lazy_static = "1.4.0"
dotenv = "0.15.0"
