[package]
name = "utxo-in-memory"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "UTXO State management system with in-memory storage ans psql persisitence"
repository.workspace = true
readme = "README.md"
categories = ["cryptography", "blockchain"]
keywords = ["cryptography", "blockchain", "zero-knowledge", "bulletproofs","vm", "smart-contracts"]
publish = false

# documentation = "https://docs.rs/utxo-memory"
# license, repository, authors inherited from [workspace.package]


# [[bin]]
# name = "api_server"

[dependencies]
# shared dependencies
curve25519-dalek.workspace = true
serde.workspace = true  
serde_json.workspace = true
bincode.workspace = true
hex.workspace = true
rand.workspace = true
merlin.workspace = true

dotenv = "0.15.0"
jsonrpc = "0.12.1"
jsonrpc-http-server = "18.0"
jsonrpc-core = "18.0.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
lazy_static = "1.4.0"
jsonrpsee = "0.16.2"
getrandom = { version = "0.2", default-features = false, features = ["js"] }
uuid = { version = "0.8.2", features = ["v4", "serde"] }
stopwatch = "0.0.7"
rusty-leveldb = "1.0.6"
tungstenite = "0.15.0"
url = "2.4.0"
postgres = { version = "0.19.2", features = ["with-serde_json-1", "array-impls"] }
postgres-types = { version = "0.1.0", features = ["derive", "with-serde_json-1"] }
r2d2 = "0.8.9"
r2d2_postgres = "0.18.1"
temp-env = "0.3.4"
prometheus = "0.12"
serde_ini = "0.2"

[dependencies.quisquis-rust]
workspace = true

[dependencies.transaction]
path = "../transaction"

[dependencies.zkvm]
path = "../zkvm"

[dependencies.address]
path = "../address"

[dependencies.chain-oracle]
path = "../chain-oracle"
