[package]
name = "transactionapi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.131"
serde_derive = "1.0.131"
serde_json = "1.0.68"
dotenv = "0.15.0"
jsonrpc = "0.12.1"
jsonrpc-http-server = "18.0"
jsonrpc-core = "18.0.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
lazy_static = "1.4.0"

jsonrpsee = "0.16.2"

curve25519-dalek = { version = "3", features = ["serde"] }
merlin = "2"
# tendermint-rpc = "0.28.0"
# check bitcoin core rpc 

[dependencies.quisquis-rust]
path = "../../../quisquis-rust"

[dependencies.transaction]
path = "../transaction"

[dependencies.elgamalsign]
path = "../elgamalsign"

[dependencies.bulletproofs]
git = "https://github.com/dalek-cryptography/bulletproofs"
branch = "develop"
features = ["yoloproofs"]

[features]
default = []
nightly = ["curve25519-dalek/nightly", "curve25519-dalek/alloc"]



[workspace]




members = []