[package]
name = "rangeproof"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Programmable range proof construction using Bulletproofs R1CS framework."
repository.workspace = true
keywords = ["cryptography", "crypto", "bulletproof", "spacesuit", "cloak"]
categories = ["cryptography"]
publish = false

# documentation = "https://docs.rs/"
# license, repository, authors inherited from [workspace.package]
[dependencies]
thiserror.workspace = true
merlin.workspace = true
rand.workspace = true
subtle.workspace = true
curve25519-dalek.workspace = true
serde.workspace = true
bulletproofs.workspace = true

[features]
default = []
nightly = ["curve25519-dalek/alloc", "subtle/nightly", "bulletproofs/nightly"]

[dev-dependencies]
criterion = "0.2"

