[package]
name = "mulmsgsig"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Multi-message multi-signature scheme for Ristretto255 with batch verification support."
repository.workspace = true
keywords = ["cryptography", "crypto", "signatures", "schnorr", "multi-message", "verification"]
categories = ["cryptography"]
publish = false

# documentation = "https://docs.rs/merkle"
# license, repository, authors inherited from [workspace.package]

[dependencies]
thiserror.workspace = true
merlin.workspace = true
rand.workspace = true
subtle.workspace = true
curve25519-dalek.workspace = true
serde.workspace = true

[dependencies.starsig]
path = "../starsig"

[features]
default = []
nightly = ["curve25519-dalek/alloc", "subtle/nightly"]


